v 1.1.3 - cosmetic changes

diff --git a/hb-archive b/hb-archive
--- a/hb-archive
+++ b/hb-archive
@@ -1,5 +1,5 @@
 #!/bin/bash
-#####################################################################
+###############################################################################
 # Script Name  : hb-archive (Version 1.0.2)
 # Description  : archive HomeBank 5.2.3 backup files from the previous month
 # Dependencies : case, cat, clear, date, find, zip
@@ -8,12 +8,12 @@
 # Email        : rick.romig@gmail.com
 # Comments     : Run on the last date of the month!
 #              : Script will not run prior to the 21st day of the month.
-# The leapyear function is adpated from a nixCraft shell script,
+# The leapyear function is adapted from a nixCraft shell script,
 # Copyright (c) 2005 nixCraft project <http://cyberciti.biz/fb/>, licensed under
 # GNU GPL version 2.0 or above.
 # The original leapyear script is part of nixCraft shell script collection (NSSC)
-# Visit http://bash.cyberciti.biz/ for more information.
-#####################################################################
+# Visit <http://bash.cyberciti.biz/> for more information.
+###############################################################################
 # Copyright (C) 2019, Richard B. Romig
 # Email: rick.romig@gmail.com
 #
@@ -29,18 +29,16 @@
 #
 # You should have received a copy of the GNU General Public License along
 # with this program. If not, see <https://www.gnu.org/licenses/>.
-
-
-## Functions
+###############################################################################
 
 # Display info page
 hba_info () {
   clear
   cat << _EOF_
 
-$scriptname, $version
+$SCRIPTNAME, $VERSION
 
-$progname is a script to create a monthly archive of backup files created
+$PROGNAME is a script to create a monthly archive of backup files created
 by Maxime Doyen's HomeBank program. <http://homebank.free.fr>
 
 I've used this script with HomeBank version 5.2.3  and later but it should work
@@ -78,99 +76,104 @@ _EOF_
 hba_version () {
   clear
   cat << _EOF_
-$scriptname $version, dated $lastedited
-Copyright $copyright
-$progname is a script to create an end of the month archive of backup
+$SCRIPTNAME $VERSION, dated $LASTEDITED
+$COPYRIGHT
+$PROGNAME is a script to create an end of the month archive of backup
 files created by Maxime Doyen's HomeBank program. <http://homebank.free.fr>"
 _EOF_
 }
 
-# Determine if it's a leap year
+# Determine if the current year is a leap year
 
 leapyear () {
-  year=$(date +"%Y")
-  isleap=0     # 0 = not a leap year, 1 = a leap year
+  YEAR=$(date +"%Y")
+  ISLEAP=0     # 0 = not a leap year, 1 = a leap year
 
-  if [ $(( year % 4 )) -ne 0 ] ; then
+  if [ $(( YEAR % 4 )) -ne 0 ] ; then
       : #  not a leap year : means do nothing and use old value of isleap
-   elif [ $(( year % 400 )) -eq 0 ] ; then
+   elif [ $(( YEAR % 400 )) -eq 0 ] ; then
       # yes, it's a leap year
-      isleap=1
-   elif [ $(( year % 100 )) -eq 0 ] ; then
+      ISLEAP=1
+   elif [ $(( YEAR % 100 )) -eq 0 ] ; then
       : # not a leap year do nothing and use old value of isleap
    else
       # it is a leap year
-      isleap=1
+      ISLEAP=1
    fi
-   return $isleap
+   return $ISLEAP
 }
 
-# Check to see if it's the last day of the month
+# Determine if it is an appropriate day of the month to run the script.
 
 checkdate () {
 
-  month=$(date +"%b")
-  today=$(date +"%d")
+  # Flag to be returned to determine if the script will be run.
+  # 0 = run script, 1 or 2 = don't run script
+  FLAG=1
 
-  # Check if current year is a leap year
+  # Determine if current year is a leap year
   leapyear
-  leap=$?
+  LEAP=$?
 
-  flag=1	# 0 = run script, 1 or 2 = don't run script
+  CURMONTH=$(date +"%b")
+  TODAY=$(date +"%d")
 
-  case $month in
-    Feb)  if (( leap == 0 )); then
-            [ "$today" -eq "28" ] && flag=0
+  # Determin if it is the last day of the month
+  case $CURMONTH in
+    Feb)  if (( LEAP == 0 )); then
+            [ "$TODAY" -eq "28" ] && FLAG=0
           else
-            [ "$today" -eq "29" ] && flag=0
+            [ "$TODAY" -eq "29" ] && FLAG=0
           fi
           ;;
-    Apr|Jun|Sep|Nov)  [ "$today" -eq "30" ] && flag=0 ;;
-    *)  [ "$today" -eq "31" ] && flag=0 ;;
+    Apr|Jun|Sep|Nov)  [ "$TODAY" -eq "30" ] && FLAG=0 ;;
+    *)  [ "$TODAY" -eq "31" ] && FLAG=0 ;;
   esac
 
   # If not the last day of the month, check if it's too early to archive
-
-  if (( flag == 1 )) && (( today < 21 )); then
-    :	# do nothing
-  elif (( flag == 1 )) && (( today >= 21 )); then
-    echo "$month $today is not the end of the month."
-    read -rp "Do you still wish to archive last month's backup files? [yN] " yn
-    case $yn in
-      [Yy]*)  flag=0 ;;	# Run the script
-      *)      flag=2 ;;	# Script canceled by user
+  if (( FLAG == 1 )) && (( TODAY < 21 )); then
+    :	# do nothing, retain original value of FLAG
+  elif (( FLAG == 1 )) && (( TODAY >= 21 )); then
+    echo "$CURMONTH $TODAY is not the end of the month."
+    read -rp "Do you still wish to archive last month's backup files? [y/N] " YN
+    case $YN in
+      [Yy]*)  FLAG=0 ;;	# Run the script
+      *)      FLAG=2 ;;	# Script canceled by user
     esac
   fi
 
-  return "$flag"
+  return "$FLAG"
 }
 
 ## Variables
 
-user=$USER
-scriptname=$(basename "$0")
-progname="HomeBank Archive"
-version="v1.1.1"
-lastedited="2019-08-21"
-copyright="(c) 2019, Richard Romig"
+MYUSER=$USER
+SCRIPTNAME=$(basename "$0")
+PROGNAME="HomeBank Archive"
+VERSION="v1.1.3"
+LASTEDITED="2019-08-26"
+COPYRIGHT="Copyright (C) 2019, Richard Romig"
 
 # Store the directory where script was launched
-curdir=$PWD
+CURDIR=$PWD
 
 # Homebank Directory Change after testing Change to HomeBank
-hbdir="/home/$user/Documents/HomeBank"
+HBDIR="/home/$MYUSER/Documents/HomeBank"
 
 # Set initial value of runflag to 1 (not okay to run archive)
-runflag=1
+RUNFLAG=1
+
+# Current date
+CURDATE=$(date +"%d %B")
 
 # Previous month
-prevmonth=$(date -d "$(date +%Y-%m-01) - 1 day" +"%B %Y")
+PREVMONTH=$(date -d "$(date +%Y-%m-01) - 1 day" +"%B %Y")
 
 # Set reference date to the first day of the current month
-refdate=$(date -d "$(date +%Y-%m-01)" +%m%d%Y)
+REFDATE=$(date -d "$(date +%Y-%m-01)" +%m%d%Y)
 
 # Create filename for previous month archive file
-hbarchive=$(date -d "$(date +%Y-%m-01) - 1 day" +%Y-%m)-backup.zip
+HBARCHIVE=$(date -d "$(date +%Y-%m-01) - 1 day" +%Y-%m)-backup.zip
 
 # Execution
 
@@ -190,57 +193,60 @@ fi
 
 clear
 echo $'\n'$"*********************************************************"
-echo "$progname $version"
-echo "Copyright (c) 2019, Richard Romig"
+echo "$PROGNAME $VERSION"
+echo "$COPYRIGHT"
 echo "Licensed under the GNU/General Public License version 2.0"
 echo "*********************************************************"
 
-checkdate
-runflag=$?
+# Check date to determine if it's okay to create the archive
 
-if (( runflag == 1 )); then
-  echo "$month $today is too early in the month to archive last month's backup files."
+checkdate
+RUNFLAG=$?
+
+if (( RUNFLAG == 1 )); then
+  echo "$CURDATE is too early in the month to archive last month's backup files."
   echo "The archive operation has been canceled by the script."
   exit
-elif (( runflag == 2 )); then
-  echo $'\n'$"The archive operation has been canceled by the user."
+elif (( RUNFLAG == 2 )); then
+  echo $'\n'$"The archive operation has been canceled by the user on $CURDATE."
   exit
+else
+  echo "Archiving on $CURDATE."
 fi
 
 # Go to the HomeBank directory from wherever you are if you're not already there
 
-[ "$curdir" != "$hbdir" ] && pushd "$hbdir" > /dev/null
+[ "$CURDIR" != "$HBDIR" ] && pushd "$HBDIR" > /dev/null 2>&1
 
 # Create the archive folder if it doesn't already exist
 
-[ -d "$hbdir/archive" ] || mkdir -p "$hbdir/archive"
+[ -d "$HBDIR/archive" ] || mkdir -p "$HBDIR/archive"
 
 # Count number of files avaailable to be archived
 
-nbu=$(find . -maxdepth 1 -type f -name \*.bak -mtime +33 | wc -l)
-if (( nbu <= 0 )); then
-  echo "No backup files for $prevmonth available to be archived."
+NBU=$(find . -maxdepth 1 -type f -name \*.bak -mtime +33 | wc -l)
+if (( NBU <= 0 )); then
+  echo "No backup files for $PREVMONTH available to be archived."
   exit
 fi
 
 # Archive previous month's backup files
 
-echo $'\n'$"Archiving $prevmonth HomeBank backup files ..."
+echo $'\n'$"Archiving $PREVMONTH HomeBank backup files ..."
 
-if zip -mtt "$refdate" "archive/$hbarchive" ./*.bak 2>/dev/null
+if zip -mtt "$REFDATE" "archive/$HBARCHIVE" ./*.bak 2>/dev/null
 then
-  echo "HomeBank backup files for $prevmonth archived."
+  echo "HomeBank backup files for $PREVMONTH archived."
   echo "HomeBank Archives:"
   ls -1 archive/
 else
-  status=$?
-  echo "No backup files for $prevmonth available to be archived."
-  echo "Zip Error Code: $status" >&2
+  STATUS=$?
+  echo "No backup files for $PREVMONTH available to be archived."
+  echo "Zip Error Code: $STATUS" >&2
 fi
 
 # Go back to where you started
 
-[ "$curdir" != "$hbdir" ] && popd > /dev/null
+[ "$CURDIR" != "$HBDIR" ] && popd > /dev/null 2>&1
 
 exit
-
