Version 1.1.0

diff --git a/hb-archive b/hb-archive
--- a/hb-archive
+++ b/hb-archive
@@ -2,12 +2,17 @@
 #####################################################################
 # Script Name  : hb-archive (Version 1.0.2)
 # Description  : archive HomeBank 5.2.3 backup files from the previous month
-# Dependencies : case, cat, clear, date, find, mktemp, mv, touch, zip
+# Dependencies : case, cat, clear, date, find, zip
 # Arguments    : none
 # Author       : Richard Romig, 30 March 2019
 # Email        : rick.romig@gmail.com
-# Comment      : Run on the last date of the month!
-# Script will not run prior to the 21st day of the month.
+# Comments     : Run on the last date of the month!
+#              : Script will not run prior to the 21st day of the month.
+# The leapyear function is adpated from a nixCraft shell script,
+# Copyright (c) 2005 nixCraft project <http://cyberciti.biz/fb/>, licensed under
+# GNU GPL version 2.0 or above.
+# The original leapyear script is part of nixCraft shell script collection (NSSC)
+# Visit http://bash.cyberciti.biz/ for more information.
 #####################################################################
 # Copyright (C) 2019, Richard B. Romig
 # Email: rick.romig@gmail.com
@@ -25,15 +30,20 @@
 # You should have received a copy of the GNU General Public License along
 # with this program. If not, see <https://www.gnu.org/licenses/>.
 
-# Fnction to display help page
-hba-help () {
 
-cat << _EOF_
+## Functions
 
-HomeBank Archive, version 1.0.4
+# Display info page
+hba_info () {
+  clear
+  cat << _EOF_
 
-hb-archive is a script to create a monthly archive of backup files created by
-HomeBank. I've used this script with HomeBank version 5.2.3 but it should work
+$scriptname, $version
+
+$progname is a script to create a monthly archive of backup files created by
+Maxime Doyen's HomeBank program. <http://homebank.free.fr>
+
+I've used this script with HomeBank version 5.2.3  and later but it should work
 with any version of HomeBank that creates a daily backup with the .bak extension
 on any Linux system based on Debian or Ubuntu.
 
@@ -42,18 +52,17 @@ previous month's backup files. For instance, running the script on March 31
 archives February's backup files. However, the script can be forced to run as
 early as the 21st of the month.
 
-Backup (*.bak) files in the ~/Documents/HomeBank directory dated earlier than
-12:01 AM on the first day of the current calendar month are moved to a temporary
-directory and then they are moved into a compressed archive file for that month
-in an archive folder. If there are no backup files in the backup folder, no
-archive file is created and the script exits. Upon exiting the script for any
-reason, the reference file and the temporary directory are deleted.
+Backup (*.bak) files in the ~/Documents/HomeBank directory dated prior the first
+day of the current calendar month are moved into a compressed archive file for
+the prior month in an archive folder. If there are no backup files in the backup
+folder, no archive file is created and the script exits.
 
 The archive subdirectory is created under ~/Documents/HomeBank if it doesn't
 already exist.
 
-The only command line arguments allowed are '--help' or '-h' to display this
-help page. Any other arguments are reported as errors.
+The only command line arguments allowed are '--help' to display this info page
+or --version to dipslay version information. Any other arguments are reported
+as errors.
 
 Please review the README.md, LICENSE, and WARRANTY in the downloaded ZIP archive
 for more information. They can also be reviewed in my repository at:
@@ -62,134 +71,174 @@ https://github.com/RickRomig/homebankarchive
 By Richard Romig (GNU/General Public License version 2.0)
 
 _EOF_
-
 }
 
-# Cleanup after exit
-cleanup () {
-  [ -f "$ref_file" ] && rm -f "$ref_file"
-  [ -d "$backup_dir" ] && rm -rf "$backup_dir"
+# Show version information
+
+hba_version () {
+  clear
+  cat << _EOF_
+$scriptname $version, dated $lastedited
+$progname is a script to create an end of the month archive of backup files
+created by Maxime Doyen's HomeBank program. <http://homebank.free.fr>"
+_EOF_
 }
 
-trap cleanup EXIT
+# Determine if it's a leap year
 
-# Variables
+leapyear () {
+  year=$(date +"%Y")
+  isleap=0     # 0 = not a leap year, 1 = a leap year
+
+  if [ $(( year % 4 )) -ne 0 ] ; then
+      : #  not a leap year : means do nothing and use old value of isleap
+   elif [ $(( year % 400 )) -eq 0 ] ; then
+      # yes, it's a leap year
+      isleap=1
+   elif [ $(( year % 100 )) -eq 0 ] ; then
+      : # not a leap year do nothing and use old value of isleap
+   else
+      # it is a leap year
+      isleap=1
+   fi
+   return $isleap
+}
+
+# Check to see if it's the last day of the month
+
+checkdate () {
+
+  month=$(date +"%b")
+  today=$(date +"%d")
+
+  # Check if current year is a leap year
+  leapyear
+  leap=$?
+
+  flag=1	# 0 = run script, 1 or 2 = don't run script
+
+  case $month in
+    Feb)  if (( leap == 0 )); then
+            [ "$today" -eq "28" ] && flag=0
+          else
+            [ "$today" -eq "29" ] && flag=0
+          fi
+          ;;
+    Apr|Jun|Sep|Nov)  [ "$today" -eq "30" ] && flag=0 ;;
+    *)  [ "$today" -eq "31" ] && flag=0 ;;
+  esac
+
+  # If not the last day of the month, check if it's too early to archive
+
+  if (( flag == 1 )) && (( today < 21 )); then
+    :	# do nothing
+  elif (( flag == 1 )) && (( today >= 21 )); then
+    echo "$month $today is not the end of the month."
+    read -rp "Do you still wish to archive last month's backup files? [yN] " yn
+    case $yn in
+      [Yy]*)  flag=0 ;;	# Run the script
+      *)      flag=2 ;;	# Script canceled by user
+    esac
+  fi
+
+  return "$flag"
+}
+
+## Variables
 
 user=$USER
-title="HomeBank Archive 1.0.4 -- Copyright (c) 2019, Richard Romig (GPL v2.0)"
+scriptname=$(basename "$0")
+progname="HomeBank Archive"
+version="v1.1.0"
+lastedited="2019-07-14"
+copyright="(c) 2019, Richard Romig"
 
 # Store the directory where script was launched
 curdir=$PWD
 
-# Homebank Directory
-hbdir="/home/$user/Documents/Homebank"
+# Homebank Directory Change after testing Change to HomeBank
+hbdir="/home/$user/Documents/HomeBank"
 
-# Set initial value of runflag to 0 (not okay to run archive)
-runflag=0
+# Set initial value of runflag to 1 (not okay to run archive)
+runflag=1
 
-# Get the current month and day
-month=$(date +"%b")
-today=$(date +"%d")
+# Previous month
+prevmonth=$(date -d "$(date +%Y-%m-01) - 1 day" +"%B %Y")
 
-# Get previous month
-prevmonth=$(date --date="-1 month" +"%B %Y")
+# Set reference date to the first day of the current month
+refdate=$(date -d "$(date +%Y-%m-01)" +%m%d%Y)
 
 # Create filename for previous month archive file
-hbarchive=$(date --date="-1 month" +"%Y-%m")
-hbarchive+="-backup.zip"
-
-# Set reference date to 12:01 AM on 1st day of the current month
-rd=$(date +"%Y%m")
-rd+="010001"
-
-# Create the reference file. Exit on error.
-if ! ref_file=$(mktemp)
-then
-  echo "Error: Failed to create reference file." >&2
-  exit 1
-fi
-
-# Change timestamp of reference file to 12:01 AM on 1st day of the month
-if ! touch -t "$rd" "$ref_file"
-then
-  echo "Error: Could not change the timestamp of the reference file." >&2
-  exit 1
-fi
-
-# Create temporary backup directory. Exit on error.
-if ! backup_dir=$(mktemp -d)
-then
-  echo "Error: Failed to create temporary directory." >&2
-  exit 1
-fi
-
-# Show help
-clear
-if [ "$1" == "--help" ] || [ "$1" == "-h" ]; then
-  hba-help
-  exit
-fi
-
-# Check for invalid argument
-if [ -n "$1" ]; then
-  echo "Error: Invalid argument. Try 'hb-archive --help' for more info." >&2
-  exit 1
-fi
-
-# Check to see if it's the last day of the month
-case $month in
-  Feb)  [ "$today" -ge "28" ] && runflag=1 ;;
-  Apr|Jun|Sep|Nov)  [ "$today" -eq "30" ] && runflag=1 ;;
-  *)  [ "$today" -eq "31" ] && runflag=1 ;;
-esac
-
-# If not the last day of the month, check if it's too early to archive
-if (( runflag == 0 )) && (( today < 21 )); then
-  echo "$title"
-  echo "$month $today is too early in the month to archive $prevmonth backup files."
-  echo "Archive operation canceled."
-  exit
-elif (( runflag == 0 )) && (( today >= 21 )); then
-  echo "$title"
-  echo "$month $today is not the end of the month."
-  read -rp "Do you still wish to archive backup files for $prevmonth? [yN]" yn
-  case $yn in
-    [Yy]*)
-      sleep 5
-      runflag=1
-      clear
-      ;;
-    *)
-      echo $'\n'$"Archive operation canceled."
-      exit
-      ;;
-  esac
-fi
+hbarchive=$(date -d "$(date +%Y-%m-01) - 1 day" +%Y-%m)-backup.zip
 
 # Execution
 
+# Check arguments
+
+if [ "$1" == "--info" ]; then
+  hba_info
+  exit
+elif [ "$1" == "--version" ]; then
+  hba_version
+  exit
+elif [ -n "$1" ]; then
+  echo -e "\e[1;41mError: Invalid argument.\e[0m" >&2
+  echo -e "/e[1;33mOnly '--info' and '--version' are acceptable arguments.\e[0m" >&2
+  exit 1
+fi
+
+clear
+echo $'\n'$"*********************************************************"
+echo "$progname $version"
+echo "Copyright (c) 2019, Richard Romig"
+echo "Licensed under the GNU/General Public License version 2.0"
+echo "*********************************************************"
+
+checkdate
+runflag=$?
+
+if (( runflag == 1 )); then
+  echo "$month $today is too early in the month to archive last month's backup files."
+  echo "The archive operation has been canceled by the script."
+  exit
+elif (( runflag == 2 )); then
+  echo $'\n'$"The archive operation has been canceled by the user."
+  exit
+fi
+
 # Go to the HomeBank directory from wherever you are if you're not already there
+
 [ "$curdir" != "$hbdir" ] && pushd "$hbdir" > /dev/null
 
 # Create the archive folder if it doesn't already exist
+
 [ -d "$hbdir/archive" ] || mkdir -p "$hbdir/archive"
 
-echo "$title"
-echo "Archiving HomeBank backup files from $prevmonth ..."
+# Count number of files avaailable to be archived
 
-# Move backup files from the previous month to the backup folder
-find ./ -maxdepth 1 -type f -iname "*.bak" -not -newer "$ref_file" -exec mv '{}' "$backup_dir"/ \;
-
-# Check for files in the backup directory
-if [ "$(ls -A "$backup_dir")" ]; then
-  echo "Creating $hbarchive ..."
-  zip -m "archive/$hbarchive" "$backup_dir/*.bak"
-  echo "HomeBank backup files for $prevmonth archived."
-else
+nbu=$(find . -maxdepth 1 -type f -name \*.bak -mtime +33 | wc -l)
+if (( nbu <= 0 )); then
   echo "No backup files for $prevmonth available to be archived."
+  exit
+fi
+
+# Archive previous month's backup files
+
+echo $'\n'$"Archiving $prevmonth HomeBank backup files ..."
+
+if zip -mtt "$refdate" "archive/$hbarchive" *.bak 2>/dev/null
+then
+  echo "HomeBank backup files for $prevmonth archived."
+  echo "HomeBank Archives:"
+  ls -1 archive/
+else
+  status=$?
+  echo "No backup files for $prevmonth available to be archived."
+  echo "Zip Error Code: $status" >&2
 fi
 
 # Go back to where you started
+
 [ "$curdir" != "$hbdir" ] && popd > /dev/null
 
 exit
